# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, ... }:

{
  imports =
    [
      ../../../system/hardware/amdgpu.nix
      ../../../system/hardware/nvidia_proprietary.nix
      # ../../../system/hardware/nvidia_mesa_nvk.nix
      ../../../system/hardware/bluetooth.nix
      ../../../system/hardware/controllers.nix
      ../../../system/hardware/openTabletDriver.nix
      inputs.nixos-hardware.nixosModules.common-cpu-amd
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" "vfio-pci" "vfio" "kvmfr" "ec_sys" ];

  boot.extraModprobeConfig = ''
    options kvmfr static_size_mb=32
    options ec_sys write_support=Y
  '';

  # other kernel modules
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-amd"
    # Virt
    "vfio-pci"
    "vfio"
    "kvmfr"
    "ec_sys"
  ];


  boot.extraModulePackages = with config.boot.kernelPackages; [
    config.boot.kernelPackages.kvmfr
  ];


  boot.supportedFilesystems = [ "btrfs" "ext4" "vfat" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f0362a99-b3b1-4fce-bbb5-c4a63e1b9c12";
    neededForBoot = true;
    options = [ "subvol=@" "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/f0362a99-b3b1-4fce-bbb5-c4a63e1b9c12";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@nix" "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/f0362a99-b3b1-4fce-bbb5-c4a63e1b9c12";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@var" "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/5c11c8ad-9148-4c58-a985-583d7989d91f";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/f0362a99-b3b1-4fce-bbb5-c4a63e1b9c12";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@boot" "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/boot/EFI" = {
    device = "/dev/disk/by-uuid/2322-B7EF";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [
    # {
    #   device = "/dev/disk/by-uuid/8b628163-a58b-40d6-8376-20e380fec43c";
    # }
  ];

  services.udisks2 = {
    enable = true;
  };

  hardware.nvidia = {
    prime = {
      offload = {
        enable = true;
        enableOffloadCmd = true;
      };

      # sync.enable = true;

      amdgpuBusId = "PCI:7:0:0";
      nvidiaBusId = "PCI:1:0:0";
    };
  };

  services.power-profiles-daemon.enable = false;
  services.tlp = {
    enable = true;
    settings = {
      CPU_DRIVER_OPMODE_ON_AC = "active";
      CPU_DRIVER_OPMODE_ON_BAT = "guided";

      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";

      CPU_ENERGY_PERF_POLICY_ON_AC = "performance";
      CPU_ENERGY_PERF_POLICY_ON_BAT = "balance_power";

      CPU_MIN_PERF_ON_AC = 0;
      CPU_MAX_PERF_ON_AC = 100;
      CPU_MIN_PERF_ON_BAT = 0;
      CPU_MAX_PERF_ON_BAT = 60;

      CPU_BOOST_ON_AC = 1;
      CPU_BOOST_ON_BAT = 0;
    };
  };

  systemd.services.ec-permissions = {
    description = "Allow gamemode group to access EC"; # slightly better than just having gamemoderun use sudo
    after = [ "sys-kernel-debug.mount" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.bash}/bin/bash -c 'chmod 0755 /sys/kernel/debug 2>/dev/null; chmod 0755 /sys/kernel/debug/ec 2>/dev/null; chgrp gamemode /sys/kernel/debug/ec/ec0/io 2>/dev/null; chmod 0660 /sys/kernel/debug/ec/ec0/io 2>/dev/null || true'";
      RemainAfterExit = true;
    };
  };

  programs.gamemodeCommands = {
    start = [
      "systemd-run --user --unit=alphicta-fan-max --property=KillSignal=SIGTERM ${./fan-max.sh}  2>/dev/null || true"
    ];
    end = [
      "systemctl --user stop alphicta-fan-max 2>/dev/null || true"
    ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
