# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, self, ... }:

{
  imports =
    [
      (self + /system/hardware/nvidia_proprietary.nix)
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  environment.systemPackages = [ pkgs.btrfs-progs ];
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/25c91452-25f4-4a3b-aed0-8bd8355e09d2";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@" "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/25c91452-25f4-4a3b-aed0-8bd8355e09d2";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@nix" "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/25c91452-25f4-4a3b-aed0-8bd8355e09d2";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@var" "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/25c91452-25f4-4a3b-aed0-8bd8355e09d2";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@home" "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/25c91452-25f4-4a3b-aed0-8bd8355e09d2";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@boot" "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/boot/EFI" = {
    device = "/dev/disk/by-uuid/7A05-B6D5";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/mnt/storage" = {
    device = "/dev/disk/by-uuid/589e0547-cc38-447f-8300-ed20b505b99e";
    fsType = "btrfs";
    options = [
      "subvol=@data"
      "compress=zstd"
      "noatime"
      "autodefrag"
      "space_cache=v2"
    ];
  };

  fileSystems."/mnt/storage/.snapshots" = {
    device = "/dev/disk/by-uuid/589e0547-cc38-447f-8300-ed20b505b99e";
    fsType = "btrfs";
    options = [
      "subvol=@snapshots"
      "compress=zstd"
      "noatime"
    ];
  };

  services.btrfs.autoScrub = {
    enable = true;
    interval = "monthly";
    fileSystems = [ "/" "/mnt/storage" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
