# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, self, ... }:

{
  imports =
    [
      (self + /system/hardware/nvidia_proprietary.nix)
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  environment.systemPackages = [ pkgs.btrfs-progs ];
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/25c91452-25f4-4a3b-aed0-8bd8355e09d2";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@" "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/25c91452-25f4-4a3b-aed0-8bd8355e09d2";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@nix" "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/25c91452-25f4-4a3b-aed0-8bd8355e09d2";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@var" "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/25c91452-25f4-4a3b-aed0-8bd8355e09d2";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@home" "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/25c91452-25f4-4a3b-aed0-8bd8355e09d2";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@boot" "noatime" "compress=zstd:3" "space_cache=v2" ];
  };

  fileSystems."/boot/EFI" = {
    device = "/dev/disk/by-uuid/7A05-B6D5";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/mnt/storage" = {
    device = "/dev/disk/by-uuid/589e0547-cc38-447f-8300-ed20b505b99e";
    fsType = "btrfs";
    options = [
      "subvol=@data"
      "compress=zstd"
      "noatime"
      "autodefrag"
      "space_cache=v2"
    ];
  };

  fileSystems."/mnt/storage/.snapshots" = {
    device = "/dev/disk/by-uuid/589e0547-cc38-447f-8300-ed20b505b99e";
    fsType = "btrfs";
    options = [
      "subvol=@snapshots"
      "compress=zstd"
      "noatime"
    ];
  };

  services.btrfs.autoScrub = {
    enable = true;
    interval = "monthly";
    fileSystems = [ "/" "/mnt/storage" ];
  };

  swapDevices = [ ];

  # setup wireguard
  networking.wireguard.interfaces.wg0 = {
    ips = [ "10.10.0.2/24" "fd10:10::2/64" ];
    privateKeyFile = "/var/lib/secrets/wireguard/private";
    peers = [{
      publicKey = "EnJ4geT4GKXCX/ubVEMFCVAIJExzYFTgdESqCWOEyDc=";
      endpoint = "yotemensus.sopy.one:51820";
      allowedIPs = [ "0.0.0.0/0" "::/0" ];
      persistentKeepalive = 25;
    }];

    postSetup = ''
      ip rule add from 10.10.0.2 table 200 || true
      ip route replace default via 10.10.0.1 dev wg0 table 200 || true
      ip -6 rule add from fd10:10::2 table 200 || true
      ip -6 route replace default via fd10:10::1 dev wg0 table 200 || true
    '';

    postShutdown = ''
      ip rule del from 10.10.0.2 table 200 || true
      ip route del default via 10.10.0.1 dev wg0 table 200 || true
      ip -6 rule del from fd10:10::2 table 200 || true
      ip -6 route del default via fd10:10::1 dev wg0 table 200 || true
    '';

    allowedIPsAsRoutes = false;
  };

  boot.kernel.sysctl = {
    "net.ipv4.conf.all.rp_filter" = 2;
    "net.ipv4.conf.default.rp_filter" = 2;
    "net.ipv4.conf.wg0.rp_filter" = 2;
    "net.ipv6.conf.all.rp_filter" = 2;
    "net.ipv6.conf.default.rp_filter" = 2;
    "net.ipv6.conf.wg0.rp_filter" = 2;
  };

  networking.firewall.checkReversePath = "loose";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
