# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, pkgs, inputs, ... }:

{
  imports =
    [
      ./hardware/amdgpu.nix
      ./hardware/nvidia_griddunlock.nix
      # ./hardware/nvidia_mesa_nvk.nix
      ./hardware/bluetooth.nix
      ./hardware/controllers.nix
      ./hardware/openTabletDriver.nix
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" "vfio-pci" "vfio" "kvmfr" ];

  boot.extraModprobeConfig = ''
    options kvmfr static_size_mb=32
  '';

  # other kernel modules
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-amd"
    # Virt
    "vfio-pci"
    "vfio"
    "kvmfr"
  ];


  boot.extraModulePackages = with config.boot.kernelPackages; [
    config.boot.kernelPackages.kvmfr
  ];


  boot.supportedFilesystems = [ "btrfs" "ext4" "vfat" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ce242705-bb0e-43c9-b9c2-3f1a3bca4cab";
    fsType = "ext4";
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/4664995f-3298-4bc7-8edb-517d1ae39e26";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@nix" "noatime" "compress=zstd" ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/4664995f-3298-4bc7-8edb-517d1ae39e26";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@var" "noatime" "compress=zstd" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CB3A-62F0";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/home/sopy/Games" = {
    device = "/dev/disk/by-uuid/1e4867ad-a94b-47ea-98b0-a03ab6ec63d0 ";
    fsType = "ext4";
    options = [ "defaults" "nofail" ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/8b628163-a58b-40d6-8376-20e380fec43c";
    }
  ];

  services.udisks2 = {
    enable = true;
  };

  hardware.nvidia = {
    prime = {
      # offload = {
      #   enable = true;
      #   enableOffloadCmd = true;
      # };

      sync.enable = true;

      amdgpuBusId = "PCI:7:0:0";
      nvidiaBusId = "PCI:1:0:0";
    };

    powerManagement.finegrained = false;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
