name: Evaluate System Configs

on: [push, pull_request]

jobs:
  evaluate:
    strategy:
      matrix:
        include:
          - system: alphicta
          - system: bethium
          - system: zetalyeh
          - system: omegantes
      fail-fast: false
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Evaluate ${{ matrix.system }} system configuration
        run: |
          set -euo pipefail

          f=$(mktemp)
          filter = "^(copying path|unpacking '|fetching git input)"

          nix eval ".#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel" \
            --json \
            --option warn-dirty false \
            2> >(tee >(grep --line-buffered -vE "$filter"  > "$f") >&2)

          status=$?

          # Evaluation produced stderr output: warnings present
          if [ -s "$f" ]; then
            exit 1
          fi

          exit $status
