name: Evaluate System Configs

on: [push, pull_request]

jobs:
  evaluate:
    strategy:
      matrix:
        include:
          - system: alphicta
            type: system
          - system: bethium
            type: system
          - system: lamsurrus
            type: vm
          - system: omegantes
            type: system
          - system: zetalyeh
            type: system
      fail-fast: false
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Evaluate ${{ matrix.system }} (${{ matrix.type }}) system configuration
        run: |
          set -euo pipefail

          case "${{ matrix.type }}" in
            system) evalTarget="config.system.build.toplevel" ;;
            vm)     evalTarget="config.system.build.vm" ;;
            *)      echo "Unknown type: ${{ matrix.type }}"; exit 1 ;;
          esac

          f=$(mktemp)
          filter="^(copying path|unpacking '|fetching git input)"

          nix eval ".#nixosConfigurations.${{ matrix.system }}.$evalTarget" \
            --json \
            --option warn-dirty false \
            2> >(tee >(grep --line-buffered -vE "$filter"  > "$f") >&2)

          status=$?

          # Evaluation produced stderr output: warnings present
          if [ -s "$f" ]; then
            exit 1
          fi

          exit $status
