name: Check Nix formatting

on: [push, pull_request]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        
      - name: Install nixpkgs-fmt
        run: nix profile install nixpkgs#nixpkgs-fmt

      - name: Check formatting
        id: format-check
        run: |
          find $GITHUB_WORKSPACE -name '*.nix' | xargs nixpkgs-fmt --check
          echo "exitcode=$?" >> $GITHUB_ENV