name: Check Nix formatting

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        
      - name: Install nixpkgs-fmt
        run: nix profile install nixpkgs#nixpkgs-fmt

      - name: Check formatting
        id: format-check
        run: |
          find $GITHUB_WORKSPACE -name '*.nix' | xargs nixpkgs-fmt --check
          echo "exitcode=$?" >> $GITHUB_ENV