name: Check Nix formatting

on: [push, pull_request]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        
      - name: Install nixpkgs-fmt
        run: nix profile install nixpkgs#nixpkgs-fmt
        
      - name: Check formatting
        id: format-check
        run: |
          nixpkgs-fmt --check ./**/*.nix
        continue-on-error: true
      - name: Report Status
        run: |
          if [ ${{ steps.format-check.outputs.exitcode }} -eq 0 ]; then
            echo "All files are formatted correctly"
          else
            echo "Some files are not formatted correctly"
            exit 1
          fi